### ISSUE TITLE
Crash evaluating the mime-type

### ISSUE THREAD

**Issue by th-lange** [philiplb/CRUDlexAmazonS3FileProcessor#1]
The function
protected function getMimeType($file)

crashes, if the mimetype cannot be evaluated (in this case: firmware for a device).

Message:
Notice: Undefined index: ******\* in *******/app/vendor/philiplb/crudlexaddons/src/CRUDlex/CRUDAmazonS3FileProcessor.php on line 229

Maybe there should be a fallback?

**Comment by philiplb** [comment]
Fixed via fbb62a9a9120eece1fc94abe5361a968b6c977cd
