### ISSUE TITLE
"Please use AWS4-HMAC-SHA256"

### ISSUE THREAD

**Issue by jmfayard** [philiplb/CRUDlexAmazonS3FileProcessor#2]
Hello, I get an error when using a bucket located in frankfurt

```
I get an error AWS::S3::Errors::InvalidRequest The authorization mechanism you have provided is not supported. Please use AWS4-HMAC-SHA256. when I try upload file to S3 bucket in new Frankfurt region. 
```

http://stackoverflow.com/a/26538266/936870
1. upgrade php aws sdk
2. add this parameter

``` diff
        $this->client = S3Client::factory([
+         'signature' => 'v4'
        ]);
```

**Comment by philiplb** [comment]
Solved by updating to the newest aws/aws-sdk-php requiring a region in the initialization so the constructor changed and so a new version of this library was just released: 0.11.0
