### ISSUE TITLE
How to render the file?

### ISSUE THREAD

**Issue by HVSoftware** [philiplb/CRUDlexAmazonS3FileProcessor#3]
Not an issue, but a question. 

I have upload the file successfully. Now it is places under url/product/1/image/the_file.png

Only how can I get the file? I see the renderFile() method. Can I use this method - and how - in order to retrieve the full image path.

Thanks in advice

**Comment by philiplb** [comment]
Hi,
you can fetch your entity by id and then render the file with that exact method:
```PHP
$entityObject = $app['crud']->getData('myEntity')->get($myId);
return $app['crud']->getData('myEntity')->renderFile($entityObject, 'myEntity', 'myFileField');
```

Feel free to reopen if there are any more questions. :)
